vich_uploader:
    db_driver: orm

    mappings:
       photos:
           uri_prefix: '%photos_dir%'
           upload_destination: '%kernel.project_dir%/public%photos_dir%'
           namer: App\Naming\PhotoSlugNamer
