vich_uploader:
    db_driver: orm

    mappings:
        photos_categories:
           uri_prefix: '%photos_dir%'
           upload_destination: '%kernel.project_dir%/%photos_dir%'
           namer: App\Naming\PhotoSlugNamer
        photos_album:
           uri_prefix: '%photos_dir%'
           upload_destination: '%kernel.project_dir%/%photos_private_dir%'
           namer: App\Naming\PhotoSlugNamer
