controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
file_controller:
    path: /file/{name}
    controller: App\Controller\FileController::getFile
